import type { Metadata } from "next";
import { Inter, Barlow_Condensed } from "next/font/google";

import "./globals.css";
import AppNavbar from "./Components/AppNavbar";

// Load Inter (default font)
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

// Load Barlow Condensed (secondary font)
const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${barlowCondensed.variable} font-sans`}
      >
        <AppNavbar />
      </body>
    </html>
  );
}
